# syntax=docker/dockerfile:1

##
## Build
##
FROM registry.cn-hangzhou.aliyuncs.com/hanxiang/golang_basic AS build

WORKDIR /app

COPY . ./
RUN go env -w GOPROXY=https://goproxy.cn,direct \
    && go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o /little_robot

##
## Deploy
##
FROM scratch

WORKDIR /app

COPY --from=build /little_robot ../little_robot
# 主要是把配置文件啥的拷贝过来
COPY --from=build /app ./


EXPOSE 3000

ENTRYPOINT ["/little_robot"]